version: '3.9'

services:
  traefik:
    image: traefik:v2.10
    command:
      - "--providers.docker.swarmmode=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--api.dashboard=true"
      - "--api.insecure=true"
      - "--certificatesresolvers.letsencrypt.acme.tlschallenge=true"
      - "--certificatesresolvers.letsencrypt.acme.email=${ACME_EMAIL:-admin@example.com}"
      - "--certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json"
      - "--log.level=INFO"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - traefik_letsencrypt:/letsencrypt
      - traefik_logs:/var/log/traefik
    networks:
      - socialtrend_net
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3

  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: ${DB_DATABASE:-socialtrend_db}
      POSTGRES_USER: ${DB_USERNAME:-socialtrend_user}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-socialtrend_pass}
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - socialtrend_net
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME:-socialtrend_user} -d ${DB_DATABASE:-socialtrend_db}"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    networks:
      - socialtrend_net
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    image: ${DOCKER_REGISTRY:-ghcr.io/gishella-46}/socialtrend-backend:${BACKEND_VERSION:-latest}
    networks:
      - socialtrend_net
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_DATABASE=${DB_DATABASE:-socialtrend_db}
      - DB_USERNAME=${DB_USERNAME:-socialtrend_user}
      - DB_PASSWORD=${DB_PASSWORD:-socialtrend_pass}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    deploy:
      replicas: 3
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: rollback
        monitor: 30s
      rollback_config:
        parallelism: 1
        delay: 5s
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 60s
      labels:
        - "traefik.enable=true"
        - "traefik.http.services.backend.loadbalancer.server.port=8000"
        - "traefik.http.routers.backend.rule=PathPrefix(`/api`)"
        - "traefik.http.routers.backend.entrypoints=web"
        - "traefik.http.routers.backend-secure.rule=PathPrefix(`/api`)"
        - "traefik.http.routers.backend-secure.entrypoints=websecure"
        - "traefik.http.routers.backend-secure.tls.certresolver=letsencrypt"
    depends_on:
      - db
      - redis

  automation:
    image: ${DOCKER_REGISTRY:-ghcr.io/gishella-46}/socialtrend-automation:${AUTOMATION_VERSION:-latest}
    networks:
      - socialtrend_net
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_DATABASE=${DB_DATABASE:-socialtrend_db}
      - DB_USERNAME=${DB_USERNAME:-socialtrend_user}
      - DB_PASSWORD=${DB_PASSWORD:-socialtrend_pass}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    deploy:
      replicas: 3
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: rollback
        monitor: 30s
      rollback_config:
        parallelism: 1
        delay: 5s
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 60s
      labels:
        - "traefik.enable=true"
        - "traefik.http.services.automation.loadbalancer.server.port=5000"
        - "traefik.http.routers.automation.rule=PathPrefix(`/automation`)"
        - "traefik.http.routers.automation.entrypoints=web"
        - "traefik.http.routers.automation-secure.rule=PathPrefix(`/automation`)"
        - "traefik.http.routers.automation-secure.entrypoints=websecure"
        - "traefik.http.routers.automation-secure.tls.certresolver=letsencrypt"
    depends_on:
      - db
      - redis

  frontend:
    image: ${DOCKER_REGISTRY:-ghcr.io/gishella-46}/socialtrend-frontend:${FRONTEND_VERSION:-latest}
    networks:
      - socialtrend_net
    environment:
      - VITE_API_URL=https://${DOMAIN:-localhost}/api
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: rollback
        monitor: 30s
      rollback_config:
        parallelism: 1
        delay: 5s
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 60s
      labels:
        - "traefik.enable=true"
        - "traefik.http.services.frontend.loadbalancer.server.port=8080"
        - "traefik.http.routers.frontend.rule=Host(`${DOMAIN:-localhost}`)"
        - "traefik.http.routers.frontend.entrypoints=web"
        - "traefik.http.routers.frontend-secure.rule=Host(`${DOMAIN:-localhost}`)"
        - "traefik.http.routers.frontend-secure.entrypoints=websecure"
        - "traefik.http.routers.frontend-secure.tls.certresolver=letsencrypt"
    depends_on:
      - backend

  celery:
    image: ${DOCKER_REGISTRY:-ghcr.io/gishella-46}/socialtrend-automation:${AUTOMATION_VERSION:-latest}
    command: celery -A tasks worker --loglevel=info
    networks:
      - socialtrend_net
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_DATABASE=${DB_DATABASE:-socialtrend_db}
      - DB_USERNAME=${DB_USERNAME:-socialtrend_user}
      - DB_PASSWORD=${DB_PASSWORD:-socialtrend_pass}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      placement:
        constraints:
          - node.role == worker
    depends_on:
      - db
      - redis
      - automation

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./docker/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention.time=30d'
      - '--web.enable-lifecycle'
    networks:
      - socialtrend_net
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:latest
    volumes:
      - grafana_data:/var/lib/grafana
      - ./docker/grafana/provisioning:/etc/grafana/provisioning:ro
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD:-admin}
      - GF_USERS_ALLOW_SIGN_UP=false
    networks:
      - socialtrend_net
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure
    ports:
      - "3000:3000"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.0
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    networks:
      - socialtrend_net
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure
    ports:
      - "9200:9200"

  logstash:
    image: docker.elastic.co/logstash/logstash:8.11.0
    volumes:
      - ./docker/logstash/pipeline:/usr/share/logstash/pipeline:ro
      - ./docker/logstash/config:/usr/share/logstash/config:ro
    networks:
      - socialtrend_net
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    environment:
      - "LS_JAVA_OPTS=-Xmx256m -Xms256m"

  kibana:
    image: docker.elastic.co/kibana/kibana:8.11.0
    volumes:
      - ./docker/kibana/kibana.yml:/usr/share/kibana/config/kibana.yml:ro
    networks:
      - socialtrend_net
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    depends_on:
      - elasticsearch
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - xpack.security.enabled=false
    ports:
      - "5601:5601"

networks:
  socialtrend_net:
    driver: overlay
    attachable: true

volumes:
  db_data:
    driver: local
  prometheus_data:
    driver: local
  grafana_data:
    driver: local
  elasticsearch_data:
    driver: local
  traefik_letsencrypt:
    driver: local
  traefik_logs:
    driver: local

